services:
  predictive_backend:
    build: .
    container_name: predictive_backend
    ports:
      - "8003:8003"
    env_file:
      - .env
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped
    networks:
      - centinela-net

networks:
  centinela-net:
    external: true
