# Uso sugerido:
# docker compose --env-file .env_produccion -f docker-compose_produccion.yaml up -d

services:
  predictive-service:
    build: .
    container_name: predictive-service
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "8003"
    env_file:
      - path: .env_produccion
        required: false
    networks:
      centinela-net:
        aliases:
          - predictive-service

networks:
  centinela-net:
    external: true
